version: '3.8'

services:
  todo-app:
    build: .
    container_name: todo-app
    ports:
      - "8080:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/todoDB
      - REDIS_HOST=redis
      - SESSION_SECRET=albion
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:redis:7.4.2-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:
